#!/usr/bin/env python3

import argparse
import pyotp
import hashlib


def main():

    parser = argparse.ArgumentParser(description='Generate TOTP codes')
    parser.add_argument('secret', metavar='SECRET', help='The secret used to generate the TOTP code')
    parser.add_argument('-d', '--digits', default=8, type=int, help='Number of digits in the generated code')

    args = parser.parse_args()

    totp = pyotp.TOTP(args.secret, digits=args.digits, digest=hashlib.sha512)
    print(totp.now())


if __name__ == '__main__':
    main()
